FROM java:8-jdk

MAINTAINER Ernesto Barbosa <jose.barbosa@cwi.com.br>

ENV WIREMOCK_VERSION 2.5.0

# Busca o wiremock
RUN mkdir -p /var/wiremock/lib/ \
  && wget https://github.com/ernestosbarbosa/wiremock/raw/master/release/wiremock-standalone-$WIREMOCK_VERSION.jar \
    -O /var/wiremock/lib/wiremock-standalone.jar

#cria o diretório
WORKDIR /home/wiremock

#expõe as portas
EXPOSE 8081

RUN apt-get update
RUN	apt-get install -y git && \
	git config --global user.email "jose.barbosa@cwi.com.br" && \
	git config --global user.name "jose.barbosa" && \
	echo "10.0.100.12 git.cwi.com.br" >> /etc/hosts 
#	git clone http://<usuario>:<senha>@10.0.100.12/jose.barbosa/wiremock-stubs.git /home/wiremock/
#substituir <usuario> e <senha> pela sua senha antes do build

#busca a extensão
#ADD https://repo1.maven.org/maven2/com/opentable/wiremock-body-transformer/1.1.3/wiremock-body-transformer-1.1.3.jar /var/wiremock/extensions/
ADD https://github.com/ernestosbarbosa/wiremock/raw/master/release/wiremock-body-transformer-1.1.4.jar /var/wiremock/extensions/

#cria o volume
#VOLUME /home/wiremock

#executa o wiremock com a extensão
#CMD ["java", "-cp", "/var/wiremock/lib/*:/var/wiremock/extensions/*", "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner"]
#CMD ["java", "-cp", "/var/wiremock/lib/*:/var/wiremock/extensions/*", "com.github.tomakehurst.wiremock.standalone.WireMockServerRunner", "--extensions", "com.opentable.extension.BodyTransformer"]

CMD git clone http://<usuario>:<senha>@10.0.100.12/jose.barbosa/wiremock-stubs.git /home/wiremock/ && java -cp /var/wiremock/lib/*:/var/wiremock/extensions/* com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions com.opentable.extension.BodyTransformer
